/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    @Test void testRollGenerateArrayWithRightLength(){
        // 1 Arrange
        // system under test
        Library sut = new Library();
        //Act
        int[] result = sut.roll(5);
        //Assert
        Assertions.assertEquals(5 , result.length);
    }

    @Test void testContainsDuplicates_returnTrueIfThereIsDuplicates(){
        // 1 Arrange
        // system under test
        Library sut = new Library();
        //Act
        int[] arr1 = {1, 2, 3, 4, 1};
        int[] arr2 = {1, 2, 3, 4};
        boolean result1 = sut.containsDuplicates(arr1);
        boolean result2 = sut.containsDuplicates(arr2);

        //Assert
        Assertions.assertEquals(true,result1);
        Assertions.assertEquals(false,result2);
    }

    @Test void testCalculatingAverages(){
        // 1 Arrange
        // system under test
        Library sut = new Library();
        //Act
        int[] arr = {1, 2, 3};
        double result = sut.calculatingAverages(arr);

        //Assert
        Assertions.assertEquals(2,result);
    }

    @Test void testLowestAverageArray(){
        // 1 Arrange
        // system under test
        Library sut = new Library();
        //Act
        int[][] arr = {
                {1, 2, 3, 4 ,5},
                {3, 4, 5, 6, 7},
                {5, 6, 7, 8, 9}
        };
         int[] result = sut.lowestAverageArray(arr);

        //Assert
        Assertions.assertEquals(arr[0],result);
    }

}
