/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Random;

public class Library {

    public static void main(String[] args) {

        int[][] arr = {
                {1, 1, 1, 1, 1, 1, 1},
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {7, 5, 5, 0, 2, 5, 1},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57},
                {66, 64, 58, 65, 71, 57, 60},
                {166, 164, 158, 165, 171, 157, 160}
        };

        int[] x = {66, 64, 58, 65, 71, 60};

        printArray(roll(5));

        System.out.println("****************************");

        System.out.println(calculatingAverages(x));

        System.out.println("****************************");

        System.out.println(containsDuplicates(x));

        System.out.println("****************************");

        lowestAverageArray(arr);

    }


    // Roll Function
    public static int[] roll(int n) {
        int[] arr = new int[n];
        Random random = new Random();
        for (int i = 0; i < arr.length; i++) {
            int randomNumber = random.nextInt(6) + 1;
            arr[i] = randomNumber;
        }
        return arr;
    }

    // =====================================

    // Function to Print the result from roll Function
    public static void printArray(int[] arr) {
        for (int j : arr) {
            System.out.print(j + " ");
        }
    }

//=======================================

    // containsDuplicates Function
    public static boolean containsDuplicates(int[] arr) {
        for (int i = 0; i < arr.length - 1; i++) {
            for (int j = i + 1; j < arr.length; j++) {
                if (arr[i] == arr[j]) {
                    return true;
                }
            }
        }
        return false;
    }

// =====================================

    // calculatingAverages Function
    public static double calculatingAverages(int[] arr) {
        double sum = 0;
        int count = 0;
        for (int j : arr) {
            sum = sum + j;
            count++;
        }
        return sum / count;
    }

// ======================================

    public static int[] lowestAverageArray(int[][] arr) {

        int[] lowestAverageArray = new int[arr.length];
        double lowestAverage = 99999; // make the initial value very large (To change with first comparison with currentAverage )
        for (int[] ints : arr) {
            double currentAverage = calculatingAverages(ints);
            if (currentAverage < lowestAverage) {
                lowestAverage = currentAverage;
                lowestAverageArray = ints;
            }
        }
        System.out.println("lowest Average : " + lowestAverage);
        System.out.print("lowest Average Array : ");
        printArray(lowestAverageArray);
        return lowestAverageArray;
    }


}